### ISSUE TITLE
"Statement too complex" error on import

### ISSUE THREAD

**Issue by dooniem** [cristianbuse/VBA-UserForm-MouseScroll#13]
Hi, I want to try out your mouse scroll solution but get the error "Statement too complex" on both the .bas and the .cls file on import.
Tried in both 32bit and 64bit environment.

I'm inside VBE, rightclick and then import file. Is that wrong?

**Comment by cristianbuse** [comment]
Hi,

I've just tried and it works fine for me.

Maybe you've made a copy of the raw text displayed by GitHub and maybe there is some problem with new line characters.
Please try downloading the [zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/archive/refs/heads/master.zip) and then import from the 'src' folder.

**Comment by cristianbuse** [comment]
Glad it worked. Yeah, I think you could also copy the raw data and paste it into a text file:  
![img](https://i.stack.imgur.com/QdWGV.png)

but not the browser's Save As feature

**Comment by DeerSpotter** [comment]
downloading the source and using the one in zip worked for me.
