### ISSUE TITLE
can not import these two files into excel

### ISSUE THREAD

**Issue by iccor56** [cristianbuse/VBA-UserForm-MouseScroll#14]
using excel 2016 x64 version

upon import MS visual basic for applications says "statement too complex"

do you have any ideas?

**Comment by cristianbuse** [comment]
Hi @iccor56 ,

How did you import? Have you downloaded the files and imported them or have you done a copy-paste of the code?

I tested on both x32 and x64 in Office 365, Office 2016 and Office 2013 and it works fine for me hence my question above.

**Comment by iccor56** [comment]
Downloaded and import
