### ISSUE TITLE
Variable not defined

### ISSUE THREAD

**Issue by piotrpoletek** [cristianbuse/VBA-UserForm-MouseScroll#16]
Hi,

I'm trying to use the code in my form, but I get Variable not defined error for MouseOverControl in 
    For Each frmCtrl In uForm.Controls
        subControls.Add MouseOverControl.CreateFromControl(frmCtrl, hWndForm)
    Next frmCtrl

I can't figure out what to do. Could You help?

**Comment by cristianbuse** [comment]
Hi @piotrpoletek ,

It's very difficult for me to say what is wrong as the code works fine on my computers.

I would suspect this is a runtime error as the code compiles fine. Can you confirm?

If you step through code line by line, does the issue happen for a specific control?

Thanks!

**Comment by piotrpoletek** [comment]
Hi,

Could you check in attached file? Thanks.

[Mouse_Scroll.zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/files/9218864/Mouse_Scroll.zip)

**Comment by cristianbuse** [comment]
@piotrpoletek 

The actual class has a default instance. You can see that on [line 8](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/blob/master/src/MouseOverControl.cls#L8) of the ```MouseOverControl``` class.

However, those attributes do not come through when you just copy-paste code. So, you must import the module instead.

Just download the [zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/archive/refs/heads/master.zip), extract the files and then just import the class file in your project (not copy-paste code).

**Comment by cristianbuse** [comment]
@piotrpoletek 

You should not use the default instance of a userform. Maybe read [this](https://rubberduckvba.wordpress.com/2017/10/25/userform1-show/) article to understand why.

 I updated your file and it works.

[Mouse_Scroll.zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/files/9220858/Mouse_Scroll.zip)

**Comment by piotrpoletek** [comment]
@cristianbuse 
I managed to implement it in my form. Thanks a lot again.
I'll explore default instances.

**Comment by piotrpoletek** [comment]
@cristianbuse 
Could take a look at one more thing?
In attached form please put sth into for example "total current assets 2022". Close the form and open again. Scrolling will be disabled.
If You remove value from "total current assets 2022", close the form and open again scrolling will be enabled again.
I was checking if it's caused by disabled boxes but no.
Sorry for total mess in code.
[Form.zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/files/9223719/Form.zip)

**Comment by cristianbuse** [comment]
@piotrpoletek 

Your message came through to my email but not here.

Anyway, try replacing this:  
```VBA
Private Sub UserForm_QueryClose(Cancel As Integer, CloseMode As Integer)
    If CloseMode = vbFormControlMenu Then
        Call save
    End If
End Sub
```
with this:  
```VBA
Private Sub UserForm_QueryClose(Cancel As Integer, CloseMode As Integer)
    If CloseMode = vbFormControlMenu Then
        save
        Cancel = True
        Me.Hide
    End If
End Sub
```
For me it works even without this change but please do try and let me know if it fixes your issue.
