### ISSUE TITLE
Calculated fileds

### ISSUE THREAD

**Issue by piotrpoletek** [cristianbuse/VBA-UserForm-MouseScroll#17]
Hi Cristian,

thanks for your email
In attached form, issue is probably with calculated fields.
When I turn on form with any data in calculated fields, scrolling is disabled.
With empty calculated fields it works.
I can't figure it out.

Thanks
[Form.zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/files/9235275/Form.zip)
.

**Comment by cristianbuse** [comment]
Hi Piotr,

The Zip file is empty.

**Comment by piotrpoletek** [comment]
[Form.zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/files/9236450/Form.zip)

**Comment by cristianbuse** [comment]
Hi @piotrpoletek ,

I cannot replicate the issue.

What do you mean by:
> When I turn on form with any data in calculated fields, scrolling is disabled.

?
How could I replicate that step by step?

**Comment by piotrpoletek** [comment]
Hi,

please put "1" into "total current assets 2022". Close the form. Open the form again and check scrolling.

**Comment by cristianbuse** [comment]
@piotrpoletek 

I already did that and the scrolling works even after closing and re-opening.

Maybe try adding this to the form:  
```VBA
Private Sub UserForm_Terminate()
    DisableMouseScroll Me
End Sub
```
to force the unhook. But this is generally not needed.
