### ISSUE TITLE
Debugger doesn't work

### ISSUE THREAD

**Issue by Arnnaud** [cristianbuse/VBA-UserForm-MouseScroll#19]
When using the VBA MouseScroll tool, the vba debugger doesn't work and if I use a breakpoint, excel has to restart without working with debugger. 
The problems occurs with every files using the tool. 
I precise that the tool works fine with my files, the problem is only with the debugger so when I have to use the debugger, I "neutralize" this line : 
   'HookMouseToForm Me

[EDIT] : Sorry I just saw that it is a known problem with apparently no possible fix. 
In my case I use office 2021 64 bit
Anyway I just don't active it if I have to debug

**Comment by cristianbuse** [comment]
@Arnnaud Yes, indeed there is no fix for this, unless I change the approach and move away from the mouse hook entirely. I have some ideas but it's unlikely I will have time to rewrite the repo in the next year or so.

**Comment by cristianbuse** [comment]
Starting 76a384fb50d5bb2a5f6de49e287fe2fb774472d6 both Modal and Modeless forms are supported while debugging also works.
