### ISSUE TITLE
Windows 11 Office 365 64 bit

### ISSUE THREAD

**Issue by bigdaddymccarron** [cristianbuse/VBA-UserForm-MouseScroll#23]
We are having an issue getting this to work on Windows 11 running Office 365 64 bit.  When we open the form Excel would just crash.  If we uninstall Office 365 64 bit and install Office 365 32 bit the scroll logic works.

**Comment by cristianbuse** [comment]
Hi, try following the steps in issue #22. I am not able to replicate the issue.

**Comment by cristianbuse** [comment]
Starting 76a384fb50d5bb2a5f6de49e287fe2fb774472d6 both Modal and Modeless forms are supported while debugging also works. A crash is now possible in a very limited scenario and can only be triggered by the user on purpose.
