### ISSUE TITLE
Laggy and not working properly

### ISSUE THREAD

**Issue by phobo3s** [cristianbuse/VBA-UserForm-MouseScroll#24]
i am using windows 10 64 bit and 
Ms Office 365 Version 2302 

i have tried your example file but it is very laggy. even not working. 1 scroll takes 10 seconds and even then there is no scroll happening. There must be some kind of malfunction on my computer but i can't find it. is there a way to debug on analyze the situation. 
i understand that VBE is out of the options when we using this module. Can you help me?

**Comment by cristianbuse** [comment]
Hi @phobo3s ,

Indeed, code breaks would disable the mouse hook in order to prevent crashes. So, stepping through code is not an option while the hook is on.

You could add a few ```Debug.Print``` statements in the [MouseProc](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/blob/31978bd0dca0bd9505573666fdca4a8869864cdf/src/MouseScroll.bas#L422-L530) method and turn some of the logic off to see what happens.

For example, replace the ```MouseProc``` method with this shorter version:  
```VBA
#If Mac Then
#Else
#If VBA7 Then
Private Function MouseProc(ByVal ncode As Long _
                         , ByVal wParam As Long _
                         , ByVal lParam As LongPtr) As LongPtr
#Else
Private Function MouseProc(ByVal ncode As Long _
                         , ByVal wParam As Long _
                         , ByVal lParam As Long) As Long
#End If
    Dim mStruct As MOUSEHOOKSTRUCTEX
    If IsVBEActive Then GoTo Unhook
    RemoveDestroyedForms
    If m_hWndAllForms.Count = 0 Then GoTo Unhook
    If CBool(IsWindowEnabled(m_hWndMainOwner)) Then GoTo Unhook
    If m_lastHoveredControl Is Nothing Then GoTo NextHook
    If Not CBool(IsWindowEnabled(m_lastHoveredControl.FormHandle)) Then GoTo NextHook
    CopyMemory mStruct, ByVal lParam, LenB(mStruct)
    If ncode = HC_ACTION Then
        If wParam = WM_MOUSEWHEEL Or wParam = WM_MOUSEHWHEEL Then
            Debug.Print mStruct.mouseData, Timer
        End If
    End If
    '
NextHook:
    MouseProc = CallNextHookEx(0, ncode, wParam, ByVal lParam)
Exit Function
Unhook:
    UnHookMouse
    GoTo NextHook
End Function
#End If
```
and then start the demo while having the VBE window side by side. You should be seeing the scrolls generate lines in the Immediate window like so:  
![image](https://user-images.githubusercontent.com/23198997/228494715-ea8b7653-19b6-44d4-be82-b2aeea9d7b8a.png)

If there is still lag then, the issue is probably caused by a delay in callback being called from outside. Please let me know how it goes.

**Comment by phobo3s** [comment]
thank you for your response. 
i have made the changes and more i added few debug.print statements 
the code looks like that now;

```
#If Mac Then
#Else
#If VBA7 Then
Private Function MouseProc(ByVal ncode As Long _
                         , ByVal wParam As Long _
                         , ByVal lParam As LongPtr) As LongPtr
#Else
Private Function MouseProc(ByVal ncode As Long _
                         , ByVal wParam As Long _
                         , ByVal lParam As Long) As Long
#End If
    Dim mStruct As MOUSEHOOKSTRUCTEX
    If IsVBEActive Then GoTo Unhook
    RemoveDestroyedForms
    If m_hWndAllForms.Count = 0 Then GoTo Unhook
    Debug.Print m_hWndAllForms.Count
    If CBool(IsWindowEnabled(m_hWndMainOwner)) Then GoTo Unhook
    Debug.Print "checkpoint0"
    If m_lastHoveredControl Is Nothing Then GoTo NextHook
    Debug.Print "checkpoint1"
    If Not CBool(IsWindowEnabled(m_lastHoveredControl.FormHandle)) Then GoTo NextHook
    Debug.Print "checkpoint2"
    CopyMemory mStruct, ByVal lParam, LenB(mStruct)
    Debug.Print "checkpoint3"
    If ncode = HC_ACTION Then
        Debug.Print "checkpoint4"
        If wParam = WM_MOUSEWHEEL Or wParam = WM_MOUSEHWHEEL Then
            Debug.Print "checkpoint5"
            Debug.Print mStruct.mouseData, Timer
        End If
    End If
    '
NextHook:
    Debug.Print "checkpoint-next"
    MouseProc = CallNextHookEx(0, ncode, wParam, ByVal lParam)
Exit Function
Unhook:
    UnHookMouse
    GoTo NextHook
End Function
#End If
```

and i get the following debug prints.


```
 1 
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint4
checkpoint5
-78643200      50368,45 
checkpoint-next
 1 ' i think theese are normal mouse moves
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint-next
 1 
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint-next
 1 
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint-next
 1 
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint-next
 1 
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint-next
 1 
checkpoint0
checkpoint1
checkpoint2
checkpoint3
checkpoint4
checkpoint5
-47185920      50373,59 
checkpoint-next

```
it seems like normal things are happening but evet dragging the userform takes 3 seconds. 
it makes userform generally slow. Is this routine registers on my mouse and can it be stacking?

**Comment by cristianbuse** [comment]
@phobo3s ,

The routine add a mouse hook in the hook chain of the system. There might be another hook causing the issue.

Are you by any chance using any 3rd party mouse software like X-Mouse Button Control. If yes, see [this](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/issues/20#issuecomment-1348040451) workaround.

**Comment by cristianbuse** [comment]
The hook chain is managed by the operating system. My hook is attached to the Application main thread so if you crashed it then the hook got removed by the system anyway.

If you don't have any mouse software then the next thing you could try is to run Windows in Safe Mode and then try my demo. If if works fine then there must be some installed software interfering with it.

**Comment by phobo3s** [comment]
i debugged everwhere and find out this line is creating the lag
`CopyMemory mStruct, ByVal lParam, LenB(mStruct)`
if i comment this out, `Debug.Print mStruct.mouseData, Timer` this part runs like a river. But program not running as well :)
why i am copying my memory so slow? is that still can be interference?

**Comment by phobo3s** [comment]
YES! At last! 
i used your library and problem resolved!!
`LibMemory.MemCopy VarPtr(mStruct), ByVal lParam, LenB(mStruct)`
used it with your memory library.
problem solved. there must be some kind of "getting slow as more used" kind of thing.
i am feeling like wizard apprentice. 
thank you for your patience and help. i learned a lot.

**Comment by cristianbuse** [comment]
@phobo3s ,

Very interesting. All API calls are slow on VBA7 and of course that's why I even created the ```LibMemory``` library because ```CopyMemory``` is about 650 times slower on my computer. However, I did not expect single calls within the ```MouseProc``` method to be so slow.

Thank you for letting me know!

I did not even have the ```CopyMemory``` initially as the ```lParam``` parameter was declared directly ```As MOUSEHOOKSTRUCTEX``` but for whatever reason that wasn't working properly in newer versions of Office.

Will make some amends to this repo! Thanks again!

**Comment by cristianbuse** [comment]
Hi @phobo3s ,

I just pushed a version without CopyMemory. Would you be able to test and see if it works?. It does not require the memory library either. Thanks!

**Comment by phobo3s** [comment]
I tested, it works perfectly. Why there is a copy memory line before then? :)
It is beyond my comprehension but i will try to understand it. thanks again.

**Comment by phobo3s** [comment]
wow. 
thank you for a lesson like explanation. i understand it very clear now.
API usage and memory management has allways been like a mystery to me. Untill now.
can you recommend me some kind of source to learn API?. Again thank you.

**Comment by phobo3s** [comment]
I understand, will try to do more different stuff. Again thank you for your time and help. 
Have a good day :)

**Comment by cristianbuse** [comment]
Thanks, you too!
