### ISSUE TITLE
MouseOverControl variable not defined

### ISSUE THREAD

**Issue by huiettcm** [cristianbuse/VBA-UserForm-MouseScroll#25]
I've added your code to a userform with lots of textboxes and comboboxes. Those are the only two controls on the userform other than labels. I am using Office 365 and the associated desktop app. I believe the Windows Common Controller reference has not been adapted for this version of excel. However, your demo file works great. I've added the class module and the regular code module no issues. When I start my form, I get a 'Variable not defined' compile error (image attached). The error is on the line `subControls.Add MouseOverControl.CreateFormControl(frmCgtrl, hWndForm)` And the MouseOverControl is highlighted. IDK why there's no instantiation of the class at that point in the AddForm sub....thoughts?

**Comment by cristianbuse** [comment]
Hi @huiettcm ,

Don't copy paste the code. Clone the repository or download the [zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/archive/refs/heads/master.zip) file and then import the modules.

**Comment by huiettcm** [comment]
PERFECT!!!! Thank you! Now I understand what I'm seeing in the text editor.
