### ISSUE TITLE
VBA UserForm MouseScroll_DEMO.xlsm won't work-> identifier expected

### ISSUE THREAD

**Issue by wrsmcode** [cristianbuse/VBA-UserForm-MouseScroll#32]
Hello Cristian,

as i tried to test this workbook today, i've get this error message: "identifier expected"

Error was stopped by the modul MouseScroll  at position:

`    #End If
#End If

#If VBA7 = 0 Then
    private Enum LongPtr   <--- here is the error
        [_]
    End Enum
#End If`

if i change the enum name to vbLongPtr, i get the message: unexpected error 35010

i can't find the error...

mfg wrsm

**Comment by cristianbuse** [comment]
Hi @wrsmcode ,

This should not happen and it's probably because of a bug in the VBA compiler on certain version. Try removing/deleting the entire Enum definition:
```VBA
#If VBA7 = 0 Then
private Enum LongPtr
[_]
End Enum
#End If
```
and it should work.

**Comment by wrsmcode** [comment]
Hello, sry for the late feedback... - i've found my error... i've rebooted my Laptop and your WB is now still working fine... -thanks a lot for it.
issue can be closed...
have a nice christmas time!
mfg Joko

**Comment by cristianbuse** [comment]
Thanks @wrsmcode ,

Hope you had a nice Christimas time as well!
