### ISSUE TITLE
Run-time error 6

### ISSUE THREAD

**Issue by don922** [cristianbuse/VBA-UserForm-MouseScroll#35]
I am using your VBA-UerForm-MouseScroll in Excel from Office 365 64-bit. BTW, I love this tool!

Strange issue here. I have a text box on a form. I load data into the text box and scrolling works fine. If the text box is empty I can move the mouse wheel and nothing happens since there is nothing to scroll. However, if there is one line of data that includes a CRLF in the textbox when I move the mouse wheel, I get an error in TBoxScrollY at line 861. A single line of text with no CRLF at the end does not produce the error.

Dim topLine As Long: **topLine = startLine - (startY - minY) / hmPerLine**

I get the following

"'Run-time error '6':"

"Overflow"

Let me know if you need any additional information.

Thanks
Don

**Comment by cristianbuse** [comment]
Many thanks @don922 ,

The last commit should fix this issue.

**Comment by don922** [comment]
That fixed it. Thanks.

Strange issue.

Don
________________________________
