### ISSUE TITLE
Not working except zooming.

### ISSUE THREAD

**Issue by kaz4ikeda** [cristianbuse/VBA-UserForm-MouseScroll#37]
I don' t know this is an issue or my simple misuse. I downloaded the zip file and, to be sure, remove and re-import the modules MouseScroll and MouseOverControll in the xlsm file. The demo macro runs without any errors but none of controls responds to mouse wheeling except zooming with control key. In the attached video, I'm wheeling a mouse when the cursor stops. 
My environment: 13th Gen Intel i7, 32GB RAM, Windows 11 23H2 22631.3296

https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/c7df893e-ba04-4667-af09-5bc3b0082562

**Comment by cristianbuse** [comment]
Hi @kaz4ikeda ,

By any chance, do you use X-Mouse Button Control (XMBC)?

If yes, then please see [this](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/issues/20#issuecomment-1348040451) for the fix. 

if no, then do you use any other specialized mouse software?

**Comment by kaz4ikeda** [comment]
Thank you for reply, @cristianbuse .
Exactly I use XMBC. And also I deeply use StrokesPlus (Older version with Lua language).
Both software was the cause of this issue. 
XMBC can be set by your suggestion, but I can't figure out coexistence of StrokesPlus and your great mouse scroll modules.

**Comment by kaz4ikeda** [comment]
After some trial and error, I found a checkbox in S+ preferences which seems to influence the VBA mouse scrolling.
As shown in the attached image, VBA scroll works after unchecking **Enable Mouse Wheel Relay** of S+.
I remember that this checkbox was initially unchecked, but check and re-uncheck finally make VBA scrolling work.
This weird behavior may be related to the fact that the function in S+ is experimental.
![20240330_2318_40443](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/26346697/df8afd7e-84ad-4bc1-bd0a-08fc840fbf7e)

**Comment by cristianbuse** [comment]
Many thanks @kaz4ikeda for your feedback!
