### ISSUE TITLE
此宏导致打开/关闭对话框中的Comobobox自动收回/Combobox bug in file dialog box

### ISSUE THREAD

**Issue by Jerry-1984** [cristianbuse/VBA-UserForm-MouseScroll#39]
![BUG](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/31561637/fb4b8322-2c09-43d8-8065-bf70ffa48864)
我不会讲英语，以下是用谷歌翻译来的。请见谅：
在运行EnableMouseScroll后会导致“打开/保存”对话框中的下拉框自动收回，无法点击！
期待作者修复！
I don't speak English, this is translated using Google.Please forgive me:
After running Enabling MouseScroll, it will cause the dropdown box in the "Open/Save" dialog box to automatically retract and cannot be clicked!
Looking forward to the author fixing it!

**Comment by cristianbuse** [comment]
Hi @Jerry-1984 ,

Are you using the latest version? I just tested this and I do not have this problem. Thanks!

**Comment by Jerry-1984** [comment]
> Hi @Jerry-1984 ,
> 
> Are you using the latest version? I just tested this and I do not have this problem. Thanks!

是的，使用的是最新版本代码，而且发现之前的几个版本也有这样的问题。
我使用Excel2007和CorelDraw2020测试都是一样的情况。
Yes, I am using the latest version of the code, and I have found that there are also similar issues in previous versions.
I tested using both Excel2007 and CorelDraw2020 and found the same situation.

**Comment by cristianbuse** [comment]
Do you have a minimal code that I can use to reproduce the issue?

**Comment by cristianbuse** [comment]
Hi @Jerry-1984 ,

Please try the last version and let me know if it works. Thank you!

**Comment by Jerry-1984** [comment]
> Hi @Jerry-1984 ,
> 
> Please try the last version and let me know if it works. Thank you!
Now,it works  very well, Thanks!!!

**Comment by cristianbuse** [comment]
Thanks for the feedback!
