### ISSUE TITLE
VBA UserForm MouseScroll settings

### ISSUE THREAD

**Issue by vovanius** [cristianbuse/VBA-UserForm-MouseScroll#40]
Hi there! You did an excellent job! All works good so far, but I have a few questions:
-first, how can I set the scroll speed (number of rows/columns scrolled per wheel tick)?
-second, how can I disable certain functions, such as zoom or horizontal scrolling, leaving only vertical scrolling?
-third, when vertically scrolling a text box, even in Your demo file, vertical slider moves a bit jerky. Not critical issue, rather cosmetic...

Thanks in advance, nice day!

**Comment by cristianbuse** [comment]
Hi @vovanius 

Thank you for the kind words! 

If you go to the Mouse Settings in Windows, you can edit the number of lines to scroll or you can even set to scroll one screen at a time. In my Windows 10 it looks like this: 
![image](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/23198997/60ce11f5-d9db-475a-b9bc-565cd8632f8c)

This repo will then detect the new settings and work accordingly. 

However, if you don't want to change the system settings for the mouse, then you can just edit the code as you wish. For example, inside the [```GetScrollAmount```](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/blob/82c66a111c6d66cde3e277d83a6e7556a12ac027/src/MouseScroll.bas#L641-L655) function you can overwrite the return value as you wish.

**Comment by vovanius** [comment]
Hello again)) Thank You for fast and informative reply! Yes, it would be very useful to add disable/enable options for every function, so user could switch them according to "here and now" needs.
Kind regards))

**Comment by cristianbuse** [comment]
Hi @vovanius ,

I've added the options as extra parameters to the ```EnableMouseScroll``` method. They are ```True``` by default but can be changed to ```False``` for each individual form, as needed. Please let me know if this works for you. Thanks!
