### ISSUE TITLE
如果两个含有此模块的宏同时运行时会发生错误 未知的错误：35010

### ISSUE THREAD

**Issue by Jerry-1984** [cristianbuse/VBA-UserForm-MouseScroll#43]
我在CorelDRAW中使用这个宏模块，如果两个含有此模块的宏同时运行时会发生错误
未知的错误：35010
然后这两个宏就再也无法启动了，点击就弹出错误35010
I use this module in CorelDRAW,If two macros containing this module run simultaneously, an error will occur
Unknown error: 35010
Then these two macros can no longer be started, and attempting to launch them will prompt error 35010

**Comment by cristianbuse** [comment]
Hi @Jerry-1984 ,

Are there 2 separate instances of the CorelDRAW application? Or, within the same application, you have 2 separate drawing projects, each having it's own code modules?

**Comment by Jerry-1984** [comment]
> Hi @Jerry-1984 ,
> 
> Are there 2 separate instances of the CorelDRAW application? Or, within the same application, you have 2 separate drawing projects, each having it's own code modules?

Multiple macro plugins can be run simultaneously in the same CorelDRAW application, each with its own module.
As shown in the figure
![7](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/31561637/cc1e6485-8716-414e-8fb8-165633b8b742)
![8](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/assets/31561637/41b79773-2583-436e-bbbd-4ec073e05644)

**Comment by cristianbuse** [comment]
@Jerry-1984 ,

In Excel, the ```MouseScroll``` module can be used inside an add-in (see [here](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/discussions/38)) and then all projects can just call the add-in using ```Application.Run "EnableMouseScroll", Me```. Meaning only the add-in needs to have the ```MouseScroll``` module and all the other projects do not have it.

However, I have no idea if you can have add-ins in CorelDRAW. Is this something you can check and let me know? Thanks!

**Comment by Jerry-1984** [comment]
I don't know how to create an addin in CorelDRAW
Now I have merged the  two macro plugins into one, and the problem seems to have been temporarily resolved. thank you!

**Comment by cristianbuse** [comment]
Thank you @Jerry-1984 ,

I will keep this issue in mind and if I ever have time I might implement some workarond.

**Comment by JamieG-UK** [comment]
I realise this is late to the party but I can add some context to this. As PowerPoint MVP, I was dealing with Microsoft on the 35010 error for over a year is 2023 and there was something up in the VBE7.dll file that was causing issues with any kind of Win32 API callback function, including TimerProc, WindowProc and MouseProc, across all M365 Office apps. I published [this article](https://brightcarbon.helpjuice.com/en_GB/troubleshooting/35010-error) to remind myself of when it finally got fixed.

**Comment by cristianbuse** [comment]
@JamieG-UK 

Thanks! I forgot to reply to this issue. I wrote [this](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/issues/41#issuecomment-2104883594) in issue #41 as well as in #27.

Anyway, useful to have an additional link explaining what the issue is.
