### ISSUE TITLE
Runtime Error '5', Bypasses Error Handling Code

### ISSUE THREAD

**Issue by OnwardCincinnati** [cristianbuse/VBA-UserForm-MouseScroll#46]
<img width="422" alt="Screenshot 2024-07-28 182246" src="https://github.com/user-attachments/assets/bf2bb892-5e9b-4f93-b077-164f32265678">

I have no idea what happened. Everything was working fine until today, it just stopped. I get a runtime error code 5 and it stops at the same line every time. 

I don't know why it's disregarding the error handling right above it. 

I've uninstalled LogiOptions+, x-mouse (it used to work with it). 

'*******************************************************************************
'Returns a boolean indicating if a Collection has a specific key
'Parameters:
'   - coll: a collection to check for key
'   - keyValue: the key being searched for
'Does not raise errors
'*******************************************************************************
Private Function CollectionHasKey(ByVal coll As Collection _
                                , ByVal keyValue As String) As Boolean
    On Error Resume Next
    coll.item keyValue <------------------------------------------ This Line
    CollectionHasKey = (Err.Number = 0)
    On Error GoTo 0
End Function

**Comment by cristianbuse** [comment]
Hi @OnwardCincinnati ,

Please check your error settings. In the VB Editor (VBE) go to Tools >> Options and then in the new pop-up dialog go to the General tab. You should have the Error trapping set to 'Break on Unhandled Errors'.

![image](https://github.com/user-attachments/assets/30160034-d65a-4533-afec-c6055f57bebf)

**Comment by cristianbuse** [comment]
@OnwardCincinnati Hi! Any updates on this?
