### ISSUE TITLE
Windows 11 (#64 bit) - Office 365 - Userform closes when another workbook is closed.

### ISSUE THREAD

**Issue by alexmckenzie1** [cristianbuse/VBA-UserForm-MouseScroll#47]
hi Christian,  Very impressive code with lots of flexibility!

I have a problem where the userform is being closed when another Excel workbook is closed. 

I replicated this on your test workbook (VBA UserForm MouseScroll_DEMO.xlsm) as well (sequence: open a form, open another Excel workbook, close the other workbook and the open form closes in the original workbook).

Windows 11
Microsoft® Excel® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20206) 64-bit

Any suggestions please?

**Comment by cristianbuse** [comment]
Hi @alexmckenzie1 

Thank you for the kind words! Can you please re-test the latest version? Thanks!

**Comment by alexmckenzie1** [comment]
Hi @cristianbuse - I have tested and it worked perfectly!  Thank you very much for turning this around so quickly :)
