### ISSUE TITLE
VBA-UserForm-MouseScroll for Modeless UserForms

### ISSUE THREAD

**Issue by Mike2069** [cristianbuse/VBA-UserForm-MouseScroll#5]
Hello Cristian,
you had created your mouse scroll function for userforms that are displayed modal.
Could you also modify the function for userforms that are displayed modeless? 

Best regards
Mike

**Comment by cristianbuse** [comment]
Hi Mike,

Unfortunately no. At least not in the foreseeable future. The approach I've used (local thread mouse hook) does not work with a modeless userform. It simply freezes VBA. A different approach is needed.

Best Regards,
Cristian

**Comment by leipengshang** [comment]
its sad.but still thanks for the amazing code

**Comment by cristianbuse** [comment]
Starting 76a384fb50d5bb2a5f6de49e287fe2fb774472d6 both Modal and Modeless forms are supported while debugging also works
