### ISSUE TITLE
ListView?

### ISSUE THREAD

**Issue by asdfghjkl2016** [cristianbuse/VBA-UserForm-MouseScroll#7]
Hi,
this is a great Project! Thank you! :)
How can I use this with ListView-Control (SP6)? 
Greetings
Max

**Comment by asdfghjkl2016** [comment]
Hi Cristian,

thank you very much. I didn't know the Issue with x64, great for testing.  
right, scroll down for yourself, thanks for the hint. But it only works if  
the focus is on the ListView. Your project works regardless of the focus.  
That's why I didn't notice it. But is there a solution for this (ListView  
without focus)?

Max


Am 11.10.2021, 10:26 Uhr, schrieb Cristian Buse ***@***.***>:

**Comment by cristianbuse** [comment]
Starting 76a384fb50d5bb2a5f6de49e287fe2fb774472d6 both Modal and Modeless forms are supported while debugging also works. There is no need to handle other controls separately (e.g. ListView) as they will work by default
