### ISSUE TITLE
Support for WebBrowser-Control?

### ISSUE THREAD

**Issue by asdfghjkl2016** [cristianbuse/VBA-UserForm-MouseScroll#8]
Hi Cristian,
it's me again. :)
Is there an way to support the WebBrowser-Control?
Greetings

**Comment by cristianbuse** [comment]
Hi Max,

Forgot to ask, can you please let me know if the WebBrowser control works? Thanks!

**Comment by cristianbuse** [comment]
Starting 76a384fb50d5bb2a5f6de49e287fe2fb774472d6 both Modal and Modeless forms are supported while debugging also works. There is no need to handle other controls separately (e.g. WebBrowser) as they will work by default
